name: Build CI

on:
  pull_request:
    branches: [ "master" ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.9
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker images
        run: |
          docker-compose -f compose.yml build
      - name: Run Docker-compose
        run: |
          docker-compose -f compose.yml up -d
          docker-compose -f compose.yml ps
